# Generated by Django 3.2.3 on 2021-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
                ('job_title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
