# Generated by Django 3.2.3 on 2021-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=120)),
                ('job_post_on', models.DateField(auto_now=True)),
                ('close', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
    ]
