# Generated by Django 3.2.3 on 2021-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20210708_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerApplicationFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('select a job category', 'select a job category'), ('Accounting', 'Accounting'), ('Business support', 'Bsiness support'), ('Communications', 'Communications'), ('Corporate Developement', 'Corporate Developement'), ('Cybersecurity', 'Cybersecurity'), ('Digital', 'Digital'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Information Technology', 'Information Technology'), ('Internship', 'Internship'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Others', 'Others')], default='select a job category', max_length=120)),
                ('career_level', models.CharField(choices=[('Select one', 'Select one'), ('Professional', 'Professional'), ('Entry Level', 'Entry Level'), ('Management', 'Management'), ('Student', 'Student')], default='select a job category', max_length=120)),
                ('Field_of_study', models.CharField(max_length=120)),
                ('overall_result', models.FloatField(max_length=5)),
                ('resume', models.FileField(upload_to='')),
                ('job_post_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
